name: 'filter by file changed operator of common lint reporter'
description: 'operator of filter report file to common lint report'
author: 'MeilCli'
branding:
  icon: layers
  color: orange
inputs:
  github_token:
    description: 'github app token, using to read and write repository'
    required: true
    default: ${{ github.token }}
  workspace_path:
    description: 'workspace path, using to convert relative path from absolute path'
  repository:
    description: 'running repository, format: owner/repository'
  pull_request:
    description: 'running pull request number'
  commit_sha:
    description: 'running commit sha'
  use_api_context:
    description: 'this option is not using this action'
    default: 'false'
  report_files:
    description: 'report file glob pattern'
    required: true
    default: 'common_lint.json'
  report_files_follow_symbolic_links:
    description: 'report file glob pattern option'
  output_path:
    description: 'output path'
    required: true
    default: 'common_lint.json'
runs:
  using: 'node20'
  main: '../../dist/operator-filter-by-file-changed.js'
