name: 'common lint reporter'
description: 'common lint reporter that can handle various lint report files'
author: 'MeilCli'
branding:
  icon: alert-circle
  color: orange
inputs:
  github_token:
    description: 'github app token, using to read and write repository'
    required: true
    default: ${{ github.token }}
  workspace_path:
    description: 'workspace path, using to convert relative path from absolute path'
  repository:
    description: 'running repository, format: owner/repository'
  pull_request:
    description: 'running pull request number'
  commit_sha:
    description: 'running commit sha'
  report_files:
    description: 'report file glob pattern'
    required: true
    default: 'common_lint.json'
  report_files_follow_symbolic_links:
    description: 'report file glob pattern option'
  report_name:
    description: 'report name, if multiple report, should be unique name'
    required: true
    default: 'Lint report'
  report_type:
    description: 'report type, value is check_run or comment or inline_comment'
    required: true
    default: 'check_run'
  conclusion_failure_threshold:
    description: 'threshold of conclution as failure'
    required: true
    default: '100'
  conclusion_failure_weight:
    description: 'weight of reported failure by lint for conclusion'
    required: true
    default: '100'
  conclusion_warning_weight:
    description: 'weight of reported warning by lint for conclusion'
    required: true
    default: '1'
  conclusion_notice_weight:
    description: 'weight of reported notice by lint for conclusion'
    required: true
    default: '0'
  outdated_resolver:
    description: 'inline_comment only option, option of how resolve when found outdated thread'
    default: 'delete_or_force_resolve_thread'
runs:
  using: 'node20'
  main: 'dist/main.js'
