on:
  workflow_call:

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v3.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        with:
          github-token: ${{ secrets.MEILCLI_BOT }}
          script: |
            github.rest.pulls.createReview(
              {
                pull_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                event: 'APPROVE'
              }
            )
