on:
  workflow_call:

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'MeilCli'
    steps:
      - run: sleep 10s
        name: wait for API&DB synchronized
        if: github.event.pull_request.title == 'update actions'
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        if: github.event.pull_request.title == 'update actions'
        with:
          github-token: ${{ secrets.MEILCLI_BOT }}
          script: |
            github.rest.pulls.merge(
              {
                pull_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              }
            )
