name: Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      # ToDo: remove and use published version
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: eslint
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: lint_context
      - uses: ./utils/import-context/
        id: lint_context
      - name: Transform report file
        uses: ./transformer/eslint/
        with:
          report_files: |
            eslint_report.json
      - name: Report lint result
        uses: ./
        with:
          report_type: 'check_run'
          report_name: 'Check Run Report'
      - name: Report lint result
        uses: ./
        if: steps.lint_context.outputs.pull_request != 'null'
        with:
          report_type: 'comment'
          report_name: 'Comment Report'
          pull_request: steps.lint_context.outputs.pull_request
