name: Report

on:
  workflow_run:
    workflows: ['CI-Master', 'CI-PR']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: result
      - uses: MeilCli/common-lint-reporter/utils/import-context@v0
        id: lint_context
      - name: Transform report file
        uses: MeilCli/common-lint-reporter/transformer/eslint@v0
        with:
          report_files: |
            eslint_report.json
      - name: Filter by file changed
        uses: MeilCli/common-lint-reporter/operator/filter-by-file-changed@v0
        if: steps.lint_context.outputs.pull_request != 'null'
        with:
          pull_request: ${{ steps.lint_context.outputs.pull_request }}
      - run: cat common_lint.json
      - name: Report lint result
        uses: MeilCli/common-lint-reporter@v0
        with:
          report_type: 'check_run'
          report_name: 'Check Run Report'
      - name: Report lint result
        uses: MeilCli/common-lint-reporter@v0
        if: steps.lint_context.outputs.pull_request != 'null'
        with:
          report_type: 'comment'
          report_name: 'Comment Report'
          pull_request: ${{ steps.lint_context.outputs.pull_request }}
      - name: Report lint result
        uses: MeilCli/common-lint-reporter@v0
        if: steps.lint_context.outputs.pull_request != 'null'
        with:
          report_type: 'inline_comment'
          report_name: 'Inline Comment Report'
          pull_request: ${{ steps.lint_context.outputs.pull_request }}
